// priority: 500
new MultiStateTooltip('kubejs:onsen_resort')
    .addDefault(Text.translatable('tooltips.kubejs.onsen_resort.default.1'))
    .addShift(Text.translatable('tooltips.kubejs.onsen_resort.shift.1'))
    .addShift(Text.translatable('tooltips.kubejs.onsen_resort.shift.2'))
    .addShift(Text.translatable('tooltips.kubejs.onsen_resort.shift.3'))
    .addCtrl(Text.translatable('tooltips.kubejs.onsen_resort.ctrl.1'))
    .addCtrl(Text.translatable('tooltips.kubejs.onsen_resort.ctrl.2'))
    .addAlt(Text.translatable('tooltips.kubejs.onsen_resort.alt.1'))
    .addAlt(Text.translatable('tooltips.kubejs.onsen_resort.alt.2'))
    .addAlt(Text.translatable('tooltips.kubejs.onsen_resort.alt.3'))
    .addAlt(Text.translatable('tooltips.kubejs.onsen_resort.alt.4'))
    .addAlt(Text.translatable('tooltips.kubejs.onsen_resort.alt.5'))
    .addAlt(Text.translatable('tooltips.kubejs.onsen_resort.alt.6'))
    .addAlt(Text.translatable('tooltips.kubejs.onsen_resort.alt.7'))
    .addAlt(Text.translatable('tooltips.kubejs.onsen_resort.alt.8'))
    .addAlt(Text.translatable('tooltips.kubejs.onsen_resort.alt.9'))
    .addAlt(Text.translatable('tooltips.kubejs.onsen_resort.alt.10'))
    .registry()