// priority: 1000
const STATUS_IDLE = 'idle'


const STATUS_ROUTE_MOVE = 'route_move'
const NBT_ROUTE_MOVE = 'routeMove'
const STANDARD_ROUTE_MOVE_DISTANCE = 3


const STATUS_FIND_POI = 'find_poi'
const NBT_FIND_POI = 'findPOI'
const STANDARD_FIND_POI_DISTANCE = 3


const STATUS_WORK_IN_POI = 'work_in_poi'
const NBT_WORK_IN_POI = 'workInPOI'
const GO_TO_TARGET_POI_DISTANCE = 3

const SUB_STATUS_MOVE_TO_CONTAINER = 1
const SUB_STATUS_RETURN_TO_POI = 2
const SUB_STATUS_START_SHOPPING = 3
const SUB_STATUS_NONE = 0


const STATUS_DISMISS = 'dismiss'
const DISMISS_SMOKE_PARTICLE_AMOUNT = 15
const DISMISS_SMOKE_PARTICLE_SPEED = 0.1
